[cri_keychain]
  enable_keychain = true 
  image_service_path = "/tmp/containerd-grpc/containerd.sock"

[pull_modes.soci_v1]
  enable = true

[fuse]
  log_fuse_operations = true

[content_store]
  type = "containerd"
  containerd_address="/tmp/containerd-grpc/containerd.sock"